---
title: "ggplot 1"
author: "Duzhi Zhao"
date: "9/26/2019"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
install.packages('hexbin')
library(tidyverse)
library(ggridges)
```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
weather_df
```
## create a ggplot
```{r}
# set for x and y axis only
ggplot(weather_df,aes(x = tmin, y = tmax)) + 
  geom_point() #geometry of the graph
```

# alternate way of making this plot
```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()
```

# saving initial plots: mostly don't use this
```{r}
scatterplot =
  weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()

scatterplot
```

# adding color
```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name))
```

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = 0.4) +
  geom_smooth(se = FALSE)
  
```

# facet
```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = 0.4) + 
  geom_smooth(se = FALSE) +
  facet_grid(~name)
```


```{r}
weather_df %>% 
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point(aes(size = prcp), alpha = 0.35) + #information on both temperature, date and precipitation
  geom_smooth(size = 2, se = FALSE)
```

## Some Extra stuff
```{r}
weather_df %>% 
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_smooth(size = 2, se = FALSE)
```

# 2d density
```{r}
weather_df %>% 
  ggplot(aes(x = date, y = tmax)) +
  geom_hex()

```

## More kinds of plots!!

```{r}
weather_df %>% 
  ggplot(aes(x = tmax, fill = name)) +
  geom_histogram(position = "dodge") + #separate bar plots next to each other instead of stacking all up 
  facet_grid(~name)
```

# Density plot
```{r}
weather_df %>% 
  ggplot(aes(x = tmax, fill = name)) +
  geom_density(alpha = 0.3)

```

# Boxplot
```{r}
weather_df %>% 
  ggplot(aes(x = name, y = tmax)) +
  geom_boxplot() #Separate each category
```

```{r}
weather_df %>% 
  ggplot(aes(x = name, y = tmax)) +
  geom_violin()
```

# ridge plots

```{r}
weather_df %>% 
  ggplot(aes(x = tmax, y = name)) +
  geom_density_ridges()
```

## Saving a plot

```{r}
ggp_ridge_temp = 
  weather_df %>% 
  ggplot(aes(x = tmax, y = name)) +
  geom_density_ridges()


ggsave("ggplot_temp_ridge.pdf", ggp_ridge_temp)
```
